# Generated by Django 4.0.5 on 2022-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_progr', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_caducidad',
            field=models.CharField(max_length=250),
        ),
    ]
