# Generated by Django 4.0.5 on 2022-07-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_progr', '0004_alter_promocion_fecha_caducidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fechaCompra', models.DateField()),
            ],
        ),
    ]
