# Generated by Django 4.0.5 on 2022-07-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_progr', '0005_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idCliente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_progr.compra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_progr.producto')),
            ],
        ),
    ]
